name: Synopsys Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  AppSec_Pipeline:
    name: Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 2.6
          
      - name: Static Analysis with Polaris Action
        uses: devsecops-test/polaris-action@v1
        with:
          polarisServerUrl: ${{secrets.POLARIS_SERVER_URL}}
          polarisAccessToken: ${{secrets.POLARIS_ACCESS_TOKEN}}
          polarisProjectName: HVP-Dev.IO
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: polaris-scan-results.sarif.json
