name: Synopsys Scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  AppSec_Pipeline:
    name: Synopsys Security Scans
    runs-on: ubuntu-latest
    
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      PROJECT: HVP-Dev.IO

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Static Analysis with Polaris
        run: |
          curl -fLOsS $POLARIS_SERVER_URL/api/tools/v2/downloads/polaris_cli-linux64.zip
          unzip -d /tmp -jo polaris_cli-linux64.zip
          /tmp/polaris --co capture.build.cleanCommands=null --co capture.build.buildCommands=null --co project.name=$PROJECT analyze -w
          
#      - name: Static Analysis with Polaris Action
#        uses: devsecops-test/polaris-action@v1
#        with:
#          polarisServerUrl: ${{secrets.POLARIS_SERVER_URL}}
#          polarisAccessToken: ${{secrets.POLARIS_ACCESS_TOKEN}}
#          polarisProjectName: HVP-Dev.IO

#      - name: Upload SARIF file
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: polaris-scan-results.sarif.json
