name: Synopsys Scan

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  AppSec_Pipeline:
    name: Synopsys Security Scans
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Static Analysis with Polaris Action
        uses: devsecops-test/polaris-action@v1
        with:
          polarisServerUrl: ${{ secrets.POLARIS_SERVER_URL }}
          polarisAccessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polarisProjectName: HVP-Dev.IO

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: polaris-scan-results.sarif.json


      - name: Software Composition Analysis with Black Duck
        uses: blackducksoftware/github-action@v2
        with:
#          version: 7
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true --detect.project.description="Demo of Dev.IO Ruby project from GitHub Pipeline" --detect.project.name="HVP-Dev.IO" --detect.project.version.phase=DEVELOPMENT --detect.bom.aggregate.name="dev.io_bom" --detect.tools="SIGNATURE_SCAN,DETECTOR"'

#--detect.project.version.name="v1.0"
#--detect.tools="SIGNATURE_SCAN,DETECTOR"'
